### ISSUE TITLE
Wrong argument

### ISSUE THREAD

**Issue by garethjax** [stephan765/Google-Search-Console-bulk-query#1]
According to the article on MOZ there is an argument "pages"

> python search_console_query.py https://www.distilled.net/ 2017-02-05 2017-02-06 --pages file_of_pages

But according to the code the real name of the argument is 

> --page_filters_file PAGE_FILTERS_FILE.

**Comment by stephan765** [comment]
Thanks for pointing this out. That sounds like a mistake in the Moz article rather than the code (the code was written before the article). I'm sure we can get that fixed in the article—that will be the most appropriate place to make the change.
